spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/delibird?characterEncoding=utf8&useUnicode=true
    username: '{cipher}ccaa55e4397f10b3503db028a9cdbeb97ae12fc8ce693eda6f098f76ceb77f42'
    password: '{cipher}aacb0bcc6532173a038eb02ecd2fe4216932741453c05831e171a36a7aec7667'