eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: '{cipher}a062b3a784a7bf28eafab01f3538254371a2563dc292ef1fcd64049c5eea8ecfc3b1621c7969fb1fabf3c60554541cf69980dc9f3b6304cc599ce67f33455e05'
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}
    lease-renewal-interval-in-seconds: 1  # 실제 서비스 시에 제거
    lease-expiration-duration-in-seconds: 2  # 실제 서비스 시에 제거

spring:
  kafka:
    bootstrap-servers: '{cipher}735d507d51c7c739fe1f1e6e9f426788742308ef4abd31f47c3bff056cf8d88ff770c3c4dd765c1bfb719fecced3f740'

token:
  secret: '{cipher}2ed59c69ee94fcf776ee34a3260438c9d76a8200237b71b244cb2e81d122ae8cff46fde9412666e1a3488780937e4f7d'
  expiration_time: 3600000

client:
  address: http://localhost:3000

gateway:
  address: http://localhost:8000

login-service:
  address: http://localhost:8080
