services:
  service-discovery:
    image: ness727/service-discovery:1.0
    ports: 
      - "8761:8761"
    container_name: service-discovery
    hostname: service-discovery
    networks:
      - my-network

  config-service:
    image: ness727/config-service:1.0
    ports: 
      - "8888:8888"
    container_name: config-service
    hostname: config-service
    networks: 
      - my-network

  gateway-service:
    image: ness727/gateway-service:1.0
    ports: 
      - "8000:8000"
    container_name: gateway-service
    hostname: gateway-service
    networks: 
      - my-network
    depends_on:
      - config-service
      - service-discovery
    environment:
      spring.config.import: optional:configserver:http://config-service:8888

  login-service:
    image: ness727/login-service:1.0
    container_name: login-service
    hostname: login-service
    depends_on:
      - gateway-service
    networks:
      - my-network
    environment:
      spring.config.import: optional:configserver:http://config-service:8888
      spring.security.oauth2.client.registration.naver.redirect-uri: http://login-service:8080/login/oauth2/code/naver
      spring.security.oauth2.client.registration.kakao.redirect-uri: http://login-service:8080/login/oauth2/code/kakao
      spring.security.oauth2.client.registration.google.redirect-uri: http://login-service:8080/login/oauth2/code/google

  user-service:
    image: ness727/user-service:1.0
    container_name: user-service
    hostname: user-service
    depends_on:
      - gateway-service
    networks:
      - my-network
    environment:
      spring.config.import: optional:configserver:http://config-service:8888
      spring.cloud.config.profile: defualt

networks:
  my-network:
    external: true
    name: delibird-network