eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://eureka:8761/eureka/'
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}
    lease-renewal-interval-in-seconds: 1  # 실제 서비스 시에 제거
    lease-expiration-duration-in-seconds: 2  # 실제 서비스 시에 제거

spring:
  kafka:
    bootstrap-servers: 'http://kafka:9092'

  cloud:
    config:
      profile: defualt
      spring.config.import: optional:configserver:http://config-service:8888

token:
  secret: '{cipher}2ed59c69ee94fcf776ee34a3260438c9d76a8200237b71b244cb2e81d122ae8cff46fde9412666e1a3488780937e4f7d'
  expiration_time: 3600000

client:
  address: http://localhost:3000

gateway:
  address: http://gateway:8000

login-service:
  address: http://login-service:8080
