services:
  service-discovery:
    image: ness727/service-discovery:1.0
    ports: 
      - "8761:8761"
    container_name: service-discovery
    hostname: service-discovery
    networks:
      - my-network

  config-service:
    image: ness727/config-service:1.0
    ports: 
      - "8888:8888"
    container_name: config-service
    hostname: config-service
    networks:
      - my-network
    environment:
      spring.kafka.bootstrap-servers: http://api.delibird.store:9092

  gateway-service:
    image: ness727/gateway-service:1.0
    ports: 
      - "8000:8000"
    container_name: gateway-service
    hostname: gateway-service
    networks: 
      - my-network
    depends_on:
      - config-service
      - service-discovery
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.profiles.active: default

  login-service:
    image: ness727/login-service:1.0
    ports:
      - "8080:8080"
    container_name: login-service
    hostname: login-service
    depends_on:
      - gateway-service
    networks:
      - my-network
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.profiles.active: default

  user-service:
    image: ness727/user-service:1.0
    container_name: user-service
    hostname: user-service
    depends_on:
      - gateway-service
    networks:
      - my-network
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.profiles.active: default

  store-service:
    image: ness727/store-service:1.0
    container_name: store-service
    hostname: store-service
    depends_on:
      - gateway-service
    networks:
      - my-network
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.profiles.active: default

  cart-service:
    image: ness727/cart-service:1.0
    container_name: cart-service
    hostname: cart-service
    depends_on:
      - gateway-service
    networks:
      - my-network
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.profiles.active: default
  
  order-service:
    image: ness727/order-service:1.0
    container_name: order-service
    hostname: order-service
    depends_on:
      - gateway-service
    networks:
      - my-network
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.profiles.active: default

networks:
  my-network:
    external: true
    name: delibird-network