spring:
  security: # OAuth2 설정
    oauth2:
      client:
        registration: #registration
          naver:
            client-name: naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-id: '{cipher}fb19b09077b3961635c844b9f219e872f7b8e7b723a3154f5cca1993018f03aacb07fc0e29b65f2226b85360189a623c'
            client-secret: '{cipher}498f0b29e6d07ecf6add3a0695c35a564fb2dc1f134a3e5d9961b4e864b68643'
          kakao:
            client-name: kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            client-id: '{cipher}715c53a78ac37c773b165789b3c106db6a01969b1c6d30d1e93634200e0d67223ff1fc0842a4471f15f35d6e76a54a7612357e6ca1a7866039a6a42eec3bbd14'
            client-secret: '{cipher}f8f1bfcc789fc3af4aeba5252beaba5d57653f01230b2fdb848b2d62e665324c257e250e4cff54de373a6e6604f3174b6c0f06f4ea3096da7adb5b6778e2d4fc'
          google:
            client-name: google
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
            client-id: '{cipher}ef3e4bf0fad021fdb57bf6adc5558f738c4f4c9bbd1c9433ec9b3799538e75f0345adecedd7c1e239d8289fc5f32335fc21773edc039956eeb2b3292431f867f116fb1eaf10adc7bade1bc1417c4deb539475302c0392bca200e31e6945dbd95'
            client-secret: '{cipher}f2323e7fa9297b4060ee727bc95ef36bc40a05d448b3e0f813e3c157c48db617f4ad2c5f654c3b5379ca57f84de58ab9e12722009cbd3f9b7b0443a97fd1992d'
        provider: #provider
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id