spring:
  security: # OAuth2 설정
    oauth2:
      client:
        registration: #registration
          naver:
            client-name: naver
            redirect-uri: https://api.delibird.store/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-id: '{cipher}77bef3a8b2893408a823bba9c6e7889a49b43a0b0f9642f332389eeda05f2b882e2484d3ea0d843f42ebf29cc10c1ac3'
            client-secret: '{cipher}08e0f724ab9017a9a97f9c7d56c8159502faa5128087ad4fa2758e7bb43f4471'
          kakao:
            client-name: kakao
            redirect-uri: https://api.delibird.store/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            client-id: '{cipher}d02236747cd7cc79ba934a428ad9cb7d01795394df5239e4d26003496c39688f916c62c9b9338f4e2d34994b30805c03cd41af0e43caa2f1ff2df593c966abc5'
            client-secret: '{cipher}2a402528266f91d83143f97e9bd22296c9b40634b995830f02f01e07b6339f34145d46fcd04af1b6d8dd2d15240f9a99a4462be162c1c64873d9fc3fe2e27d09'
          google:
            client-name: google
            redirect-uri: https://api.delibird.store/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
            client-id: '{cipher}e383815beee1d90d54b13eb26de690fcce425efea050b2760e8442157893b9d964bd8505f19c0a8605baccdbdaf3f4ce332f96861fd4226d7cfa41ca7ff0f816ae011e7a5e8acfe67490c9a3a0751989c0efa161464d9d5d4d02153e7d6fccd5'
            client-secret: '{cipher}dbf30e2771dc5ebc42d1e587c9017642b196b113e0324ac1e6af3a98265f39d86a583b277387299735bfaf01bc0a67f8733e0c186fd009906378e3060b9210e8'
        provider: #provider
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
