spring:
  security: # OAuth2 설정
    oauth2:
      client:
        registration: #registration
          naver:
            client-name: naver
            # 퍼블릭 ip로 설정
            redirect-uri: 'http://delibird.store:8080/login/oauth2/code/naver'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-id: '{cipher}04be0ed3366b300976131deeeaea6b2567ad5d1abbee01a4d5db208728fec6b36346daf76f381aa1617bd9cc9424815b'
            client-secret: '{cipher}1d97e74b86d4588471802ab84b29de1a053daa0858aca96d912b0fa7d32faa59'
          kakao:
            client-name: kakao
            # 퍼블릭 ip로 설정
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            client-id: '{cipher}4f63a512bfdd9a6e3570c70df5f17b4986727f2e28dfa7afca477b51b38e66fbba5f47e4010e3d589b0e86c53708de0a3c91a0ea7a6267158ff7061c683e51df'
            client-secret: '{cipher}9681dd084555e719ff8c91dc7ad19e065f09637c0a3da8b824975789c656fbd38652444caab6f0815172765f3ac10f739769f8101e94ec6f6529eebad1609537'
          google:
            client-name: google
            # 퍼블릭 ip로 설정
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
            client-id: '{cipher}f9f0eb3ac8b778e333dbfc0b67e9286f623023b25f30f43521fda44e2868dd28c266e0be8858ab2caaffac9c9349413d4322ad86503508e2411c1549de964a9dfb0412a5bb8bc78b1942e8766e6304acc196783dfddeef321c282aba670f0ec0'
            client-secret: '{cipher}3a9ecccaf0a3172dd373fcde4bdb273ac6b1f7fcd4e288346340ec2a90e1b91e9028a2fc3488e7fde43d668076f63a4c5843cba540d697f74a65f6a34d6b4a94'
        provider: #provider
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id